---
title: "Graphs"
author: "Rajath Prabhakar"
date: "2023-10-09"
output: html_document
---
```{r}
library(tidyverse)
library(here)
library(cowplot)
```
```{r}
here::set_here()
```

```{r}
setwd("C:/Users/14049/Desktop/Reddit-Forecasting-Project")
rank_avg <- read_csv("Results/CSV Files/Average_City_Rank.csv")
table1 <- read_csv("Results/CSV Files/table_of_average_acf_lag.csv")
combined <- read_csv("Results/CSV Files/combined_data.csv")
reddit_and_cases <- read_csv("Results/CSV Files/reddit_and_cases_deaths.csv")
```
Average Correlation

Positive
```{r}
figure1 <- ggplot(table1, aes(x = reorder(Variable,
                               abs(Average_ACF_positive)),
                   y = Average_ACF_positive))+
  geom_bar(stat = "identity")+
  coord_flip()+
  labs(x = "Average ACF",
       y = "Variable",
       title = "Variables by Average Correlations (Positive Lags)")
figure1
save_plot("Graphs/figure1.png", figure1, base_height = 8, base_width = 8)

```

Negative

```{r}
figure2 <- ggplot(table1, aes(x = reorder(Variable, -abs(Average_ACF_negative)),
                   y = Average_ACF_negative))+
  geom_bar(stat = "identity")+
  coord_flip()+
  labs(x = "Average ACF",
       y = "Variable",
       title = "Variables by Average Correlations (Negative Lags)")
figure2
save_plot("Graphs/figure2.png", figure2, base_height = 8, base_width = 8)
```

Average Rank

Positive

```{r}
figure3 <- ggplot(rank_avg, aes(x = reorder(Variable, -abs(avg_rank_pos)),
                     y = avg_rank_pos))+
  geom_bar(stat = "identity")+
  coord_flip()+
  labs(x = "Average Rank",
       y = "Variable",
       title = "Variables by Average Rank (Positive Lags)")
figure3
save_plot("Graphs/figure3.png", figure3, base_height = 8, base_width = 8)
```


Negative

```{r}
figure4 <- ggplot(rank_avg, aes(x = reorder(Variable, -abs(avg_rank_neg)),
                     y = avg_rank_neg, fill = Type))+
  geom_bar(stat = "identity")+
  coord_flip()+
  labs(x = "Average Rank",
       y = "Variable",
       title = "Variables by Average Rank (Negative Lags)")
figure4
save_plot("Graphs/figure4.png", figure4, base_height = 8, base_width = 8)
```

Average Lag

Positive
```{r}
figure5 <- ggplot(table1, aes(x = reorder(Variable, Average_Lag_positive), 
                   y = Average_Lag_positive, fill = Type))+
  geom_bar(stat = "identity")+
  coord_flip()+
  labs(x = "Average Lag",
       y = "Variable",
       title = "Variables by Average Lag (Positive Lags)")
figure5
save_plot("Graphs/figure5.png", figure5, base_height = 8, base_width = 8)
```

Negative
```{r}
figure6 <- ggplot(table1, aes(x = reorder(Variable, Average_Lag_negative), 
                   y = Average_Lag_negative, fill = Type))+
  geom_bar(stat = "identity")+
  coord_flip()+
  labs(x = "Average Lag",
       y = "Variable",
       title = "Variables by Average Lag (Negative Lags)")
figure6
save_plot("Graphs/figure6.png", figure6, base_height = 8, base_width = 8)
```



```{r}
top12variables <- c("mean_illness", "mean_health", "mean_family", "mean_Tone",
                    "mean_fatigue", "mean_Analytic", "mean_allnone", "mean_emo_pos",
                    "mean_mental", "mean_emo_sad", "mean_tone_pos", "mean_emotion")

top_12 <- combined %>% 
  filter(Lag > 0 & Variable %in% top12variables)
```

```{r}
figure7 <- ggplot(top_12, aes(x = Lag, y = Max_ACF))+
  geom_point()+
  labs(x = "Lag",
       y = "Max Correlation", 
       title = "Scatter Plot of Top 12 Reddit Indicators by Max Correlation")+
  facet_wrap(~ Variable)
figure7
save_plot("Graphs/figure7.png", figure7, base_height = 8, base_width = 8)

```

```{r}

```

```{r}
reddit_and_cases1 <- reddit_and_cases %>%
  group_by(MSA_Code) %>%
  mutate(Scaled_DailyCases7 = round(scale(Daily_Cases7), 2),
         Scaled_DailyDeaths7 = round(scale(Daily_Deaths7), 2),
         Scaled_mean_health = round(scale(mean_health), 2),
         Scaled_mean_illness = round(scale(mean_illness), 2))
```



```{r}

figure8 <- ggplot(reddit_and_cases1, aes(x = Date))+
  geom_line(aes(y = Scaled_DailyCases7, color = "Cases"))+
  geom_line(aes(y = Scaled_mean_illness, color = "mean_illness"))+
  facet_wrap(~ City, ncol = 4)+
  scale_color_manual(values = c("Cases" = "blue", "mean_illness" = "orange"))+
  labs(x = "Date",
       y = "Z Score",
       title = "Time Series of mean_illness vs Cases")+
  theme(axis.text.x = element_text(angle = 45, hjust = 1),  # Rotate x-axis labels
        axis.text = element_text(size = 10),  # Adjust font size of axis labels
        plot.margin = margin(20, 20, 20, 20))

figure7
save_plot("Graphs/figure8.png", figure8, base_height = 8, base_width = 8)
```

```{r}
figure9 <- ggplot(reddit_and_cases1, aes(x = Date))+
  geom_line(aes(y = Scaled_DailyCases7, color = "Cases"))+
  geom_line(aes(y = Scaled_mean_health, color = "mean_health"))+
  facet_wrap(~ City, nrow = 4)+
  scale_color_manual(values = c("Cases" = "blue", "mean_health" = "red"))+
  labs(x = "Date",
       y = "Z Score",
       title = "Time Series of mean_Health vs Cases")
save_plot("Graphs/figure9.png", figure9, base_height = 8, base_width = 8)
```

```{r}
head(table1 %>% filter(Average_ACF_positive > 0.1) %>% arrange(-Average_ACF_positive),10)
```
```{r}
head(rank_avg %>% arrange(avg_rank_pos), 10)
```

*CCF Plots*
```{r}
source(here::here("Results/ccf_city_case_files().R"))
```

**Atlanta**
***Health***
```{r}
ccf_city_case_files("Daily Data", "atlanta_daily.csv", explanatory = "mean_health", code = "C1206", city = "Atlanta", state = "Georgia", plots = TRUE, lags = "both")
```

**Illness**
```{r}
ccf_city_case_files("Daily Data", "atlanta_daily.csv", explanatory = "mean_illness", code = "C1206", city = "Atlanta", state = "Georgia", plots = TRUE, lags = "both")
```


**Anxiety**
```{r}
ccf_city_case_files("Daily Data", "atlanta_daily.csv", explanatory = "mean_emo_anx", code = "C1206", city = "Atlanta", state = "Georgia", plots = TRUE, lags = "both")
```


*Austin*

*Boston*

*Chicago*

